# Lefthook configuration for code quality enforcement
# https://github.com/evilmartians/lefthook

pre-commit:
  commands:
    quality-check:
      # Run all quality checks before commit
      run: make check
      fail_text: |
        ❌ Quality checks failed!

        To fix issues:
          • Run 'make format' to fix formatting
          • Fix any lint errors shown above  
          • Fix any TypeScript type errors
          • Ensure all tests pass

        Then try committing again.
