version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: spicy-claude-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=production
    volumes:
      # Mount project directories you want to access
      - /path/to/your/projects:/projects:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spicy-claude-net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: spicy-claude-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8080
    restart: unless-stopped
    networks:
      - spicy-claude-net

networks:
  spicy-claude-net:
    driver: bridge
