name: E2E Tests (Optional)

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [labeled]

jobs:
  e2e-tests:
    # Only run if manually triggered or if PR has 'e2e-test' label
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'e2e-test')
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Start backend server
        working-directory: backend
        run: |
          npm run dev &
          echo $! > backend.pid
          # Wait for server to be ready
          timeout 60 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 1; done'

      - name: Start frontend dev server
        working-directory: frontend
        run: |
          npm run dev &
          echo $! > frontend.pid
          # Wait for server to be ready
          timeout 60 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done'

      - name: Run E2E tests
        run: npm run test:ui -- --reporter=list

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/reports/
          retention-days: 7

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: tests/reports/screenshots/
          retention-days: 7

      - name: Stop servers
        if: always()
        run: |
          [ -f backend/backend.pid ] && kill $(cat backend/backend.pid) || true
          [ -f frontend/frontend.pid ] && kill $(cat frontend/frontend.pid) || true
          pkill -f "vite" || true
          pkill -f "node.*dev" || true

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';
            const emoji = status === 'success' ? '✅' : '❌';
            const body = `## ${emoji} E2E Tests ${status === 'success' ? 'Passed' : 'Failed'}

            **Status**: ${status}
            **Run**: [View Details](${context.payload.pull_request.html_url}/checks)

            ${status === 'success'
              ? '✅ All E2E tests passed!'
              : '❌ Some E2E tests failed. Check the test report artifact for details.'}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
