name: PR Quality Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    name: Quality Checks (Lint, Type, Format, Tests)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run Prettier format check (frontend)
        working-directory: frontend
        run: npm run format:check

      - name: Run Prettier format check (backend)
        working-directory: backend
        run: npm run format:check

      - name: Run ESLint (frontend)
        working-directory: frontend
        run: npm run lint

      - name: Run ESLint (backend)
        working-directory: backend
        run: npm run lint

      - name: Run TypeScript type check (frontend)
        working-directory: frontend
        run: npm run typecheck

      - name: Run TypeScript type check (backend)
        working-directory: backend
        run: npm run typecheck

      - name: Run frontend unit tests
        working-directory: frontend
        run: npm test -- --run

      - name: Run backend unit tests
        working-directory: backend
        run: npm test

      - name: Comment PR with results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ job.status }}';
            const emoji = status === 'success' ? '✅' : '❌';
            const body = `## ${emoji} Quality Checks ${status === 'success' ? 'Passed' : 'Failed'}

            **Status**: ${status}
            **Run**: [View Details](${context.payload.pull_request.html_url}/checks)

            ${status === 'success'
              ? '✅ All quality checks passed! Ready for review.'
              : '❌ Some checks failed. Please review the logs and fix any issues.'}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
